// Generated by gencpp from file beginner_tutorials/AngleArray.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ANGLEARRAY_H
#define BEGINNER_TUTORIALS_MESSAGE_ANGLEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct AngleArray_
{
  typedef AngleArray_<ContainerAllocator> Type;

  AngleArray_()
    : theta1(0.0)
    , theta2(0.0)
    , theta3(0.0)
    , alpha(0.0)
    , beta(0.0)  {
    }
  AngleArray_(const ContainerAllocator& _alloc)
    : theta1(0.0)
    , theta2(0.0)
    , theta3(0.0)
    , alpha(0.0)
    , beta(0.0)  {
  (void)_alloc;
    }



   typedef float _theta1_type;
  _theta1_type theta1;

   typedef float _theta2_type;
  _theta2_type theta2;

   typedef float _theta3_type;
  _theta3_type theta3;

   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _beta_type;
  _beta_type beta;





  typedef boost::shared_ptr< ::beginner_tutorials::AngleArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::AngleArray_<ContainerAllocator> const> ConstPtr;

}; // struct AngleArray_

typedef ::beginner_tutorials::AngleArray_<std::allocator<void> > AngleArray;

typedef boost::shared_ptr< ::beginner_tutorials::AngleArray > AngleArrayPtr;
typedef boost::shared_ptr< ::beginner_tutorials::AngleArray const> AngleArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::AngleArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::AngleArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/yoav/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::AngleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::AngleArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::AngleArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b26027db0d620ae0522c6284a86339b";
  }

  static const char* value(const ::beginner_tutorials::AngleArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b26027db0d620aeULL;
  static const uint64_t static_value2 = 0x0522c6284a86339bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/AngleArray";
  }

  static const char* value(const ::beginner_tutorials::AngleArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta1\n\
float32 theta2\n\
float32 theta3\n\
float32 alpha\n\
float32 beta\n\
";
  }

  static const char* value(const ::beginner_tutorials::AngleArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta1);
      stream.next(m.theta2);
      stream.next(m.theta3);
      stream.next(m.alpha);
      stream.next(m.beta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngleArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::AngleArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::AngleArray_<ContainerAllocator>& v)
  {
    s << indent << "theta1: ";
    Printer<float>::stream(s, indent + "  ", v.theta1);
    s << indent << "theta2: ";
    Printer<float>::stream(s, indent + "  ", v.theta2);
    s << indent << "theta3: ";
    Printer<float>::stream(s, indent + "  ", v.theta3);
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<float>::stream(s, indent + "  ", v.beta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ANGLEARRAY_H
